name: accatyyc.github.io
description: Softwhere?
meta_description: "My thoughts on programming"
#blog_cover: "/assets/images/blog_cover.jpg"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

url:            'http://accatyyc.github.io'
author:         'Joel Ekström'
